---
organisation:
    - team: "Bluetooth"
      product_owner: "Poul Erik Petersen"
      line_manager: "Henrik Stensig"
    - team: "Bluetooth Integration"
      product_owner: "Christian Hesse"
      line_manager: "Andrea Mijovic"
    - team: "Dalton"
      product_owner: "Song Chen"
      line_manager: "Kim Poulsen"
    - team: "Platform Integration"
      product_owner: "Andrei Backes"
      line_manager: "Thomas Alten"
    - team: "Signal Processing"
      product_owner: "Thorsten Birk"
      line_manager: "Andre Schmelzer"
    - team: "Platform Tooling"
      product_owner: "Erwin Arndt"
      line_manager: "Andre Schmelzer"
    - team: "Tesla"
      product_owner: "Rajeev Mahadevan"
      line_manager: "Henrik Stensig"
    - team: "Requirements"
      line_manager: "Thomas Alten"
    - team: "Architecture"
      line_manager: "Kim Poulsen"
    - team: "TestInfraOps"
      product_owner: "Pavan Kantharaju"
      line_manager: "Joerg Schuler"
    - team: "PMO"
      line_manager: "Henrik Stensig"
    - team: "Coach"
    - team: "Line"
      line_manager: "Thomas Fischer"
    - team: "Other"

    - team: "Project: F1"
      project_lead: "Prasenjeet Ghaywat"
    - team: "Project: D13"
      project_lead: "Klaus Nehmiz"
    - team: "Project: T0"
      project_lead: "Thorsten Brünnich Malajas"
    - team: "Project: D chipset"
      project_lead: "Toke Borgen Linande"
