teams:
  - name: "Tesla"
    members:
      - name: "Jakob Lykke Braad"
        birthday: "1975-01-29"
        title: "Embedded Software Developer"
      - name: "Casper Balslev Hansen"
        birthday: "1988-05-03"
        title: "Embedded Software Developer"
      - name: "Palle Lind Hansen"
        birthday: "1970-01-30"
        title: "Embedded Software Developer"
      - name: "Henrik Holm"
        birthday: ""
        title: "Embedded Software Developer"
      - name: "Emil Wessel Melgaard"
        birthday: "1987-07-31"
        title: "Embedded Software Developer"
      - name: "Ghennadie Mazin"
        birthday: ""
        title: "Embedded Software Developer"
      - name: "Per Oernboel Karkov"
        birthday: ""
        title: "Embedded Software Developer"
  - name: Bluetooth
    members:
      - name: "Robert Christensen"
        birthday: ""
        title: "Embedded Software Developer"
      - name: "Martin Lund"
        birthday: ""
        title: "Embedded Software Developer"
      - name: "Nis Lunn Madsen"
        birthday: ""
        title: "Embedded Software Developer"
      - name: "Henrik Oestergaard Madsen"
        birthday: "1963-12-21"
        title: "Embedded Software Developer"
      - name: "Morten Rudkjaer Schroeder"
        birthday: ""
        title: "Embedded Software Developer"
      - name: "Grigorii Vasilev"
        birthday: "1984-07-16"
        title: "Embedded Software Developer"
      - name: "Kim Wulf-Andersen"
        birthday: ""
        title: "Embedded Software Developer"
  - name: "Bluetooth Integration"
    members:
      - name: "Christian Hesse"
        birthday: "1984-05-26"
        title: "FW development professional"
      - name: "Salman Khan"
        birthday: "1987-06-29"
        title: "FW development professional"
      - name: "Ralf Kilank"
        birthday: ""
        title: "FW development professional"
      - name: "Joerg Lebender"
        birthday: "1967-08-02"
        title: "FW development professional"
      - name: "Rahul Singh Bhauryal"
        birthday: "1990-02-16"
        title: "FW development professional"
      - name: "Lukas Maria Streitenberger"
        birthday: "1997-01-13"
        title: "FW development professional"
  - name: "Dalton"
    members:
      - name: "Anders Eliasen"
        birthday: ""
        title: "Embedded Software Developer"
      - name: "Soeren Friis"
        birthday: "1981-06-06"
        title: "Embedded Software Developer"
      - name: "Mirek Miroslaw Fus"
        birthday: ""
        title: "Embedded Software Developer"
      - name: "Ali Batuhan Kindan"
        birthday: "1992-10-30"
        title: "Embedded Software Developer"
      - name: "Kim Varde Lassen"
        birthday: ""
        title: "Embedded Software Developer"
      - name: "Ulrik Schafer"
        birthday: ""
        title: "Embedded Software Developer"
  - name: "Platform Integration"
    members:
      - name: "Dan Mihai Iacoboae"
        birthday: "1988-01-19"
        title: "Embedded Software Developer"
      - name: "Mathivanan Naickan Palanivelu"
        birthday: "2025-05-27"
        title: "Embedded Software Developer"
      - name: "Henrik Togeby"
        birthday: ""
        title: "Embedded Software Developer"
      - name: "Hadi Jalali Lak"
        birthday: "1984-02-13"
        title: "Developer Embedded Software"
      - name: "Alper Koeker"
        birthday: ""
        title: "Developer Embedded Software"
      - name: "Bernd Beimel"
        birthday: ""
        title: "FW development professional"
      - name: "Joachim Eisenberg"
        birthday: ""
        title: "FW development professional"
      - name: "Juergen Scherg"
        birthday: ""
        title: "Developer Embedded Software"
      - name: "Florian Josef Rettelbach"
        birthday: ""
        title: "FW development professional"
      - name: "Peter Oberhofer (ext)"
        birthday: ""
        title: "Consultant"
  - name: "Signal Processing"
    members:
      - name: "Thorsten Birk"
        birthday: ""
        title: "FW development professional"
      - name: "Marcus Mertens"
        birthday: ""
        title: "FW development professional"
      - name: "Tobias Schulze"
        birthday: ""
        title: "FW development professional"
      - name: "Amer Khalouf"
        birthday: ""
        title: "FW development professional"
      - name: "Jianing Wang"
        birthday: "2025-02-07"
        title: "FW development professional"
      - name: "Bjoern Schmitz"
        birthday: "1986-07-18"
        title: "FW development professional"
      - name: "Jakob Wagner"
        birthday: ""
        title: "FW development professional"
      - name: "Harun Irak"
        birthday: "1997-02-06"
        title: "FW development professional"
      - name: "Melanie Kunkel"
        birthday: ""
        title: "FW development professional"
  - name: "Requirements"
    members:
      - name: "Ralf Anhorn"
        birthday: "2025-08-11"
        title: "Requirements Engineer"
      - name: "Aishwarya Suria Kumar"
        birthday: "1996-12-17"
        title: "Requirements Engineer"
      - name: "Michael Mai"
        birthday: ""
        title: "Requirements Engineer"
      - name: "Jesper Juul Rohde"
        birthday: "1967-05-14"
        title: "Requirements Engineer"
      - name: "Anja Hilz"
        birthday: ""
        title: "FW development professional"
  - name: "Architecture"
    members:
      - name: "Peter Kunakh"
        birthday: "1979-12-29"
        title: "Senior Architect"
      - name: "Hongyan Sun"
        birthday: ""
        title: "Senior Architect"
      - also: "Casper Balslev Hansen"
      - also: "Wanja Hofer"
      - also: "Thorsten Birk"
      - also: "Ralf Kilank"
      - also: "Tobias Schulze"
  - name: "TestInfraOps"
    members:
      - name: "Alex Belai"
        birthday: ""
        title: "DevOps Student Assistant"
      - name: "Pedro Manuel Dos Santos Gomes Diniz"
        birthday: ""
        title: "DevOps Student Assistant"
      - name: "Eriks Markevics"
        birthday: ""
        title: "DevOps Engineer"
      - name: "Erika Arioli"
        birthday: "1997-06-25"
        title: "FW development professional"
      - name: "Alexander Bielesch"
        birthday: ""
        title: "FW development professional"
      - name: "Kristian Henning Biss"
        birthday: ""
        title: "FW development professional"
      - name: "Samir El Mustafa"
        birthday: ""
        title: "FW development professional"
      - name: "Thomas Christian Kelber"
        birthday: "1966-06-12"
        title: "FW development professional"
      - name: "Patrick Moessler"
        birthday: ""
        title: "FW development professional"
      - name: "Christian Stadelmann"
        birthday: ""
        title: "FW development professional"
      - name: "Wanja Hofer"
        birthday: "1983-04-29"
        title: "FW development professional"
  - name: "Platform Tooling"
    members:
      - name: "Alexander Schmidt"
        birthday: ""
        title: "FW development professional"
      - name: "Max André Schmitt"
        birthday: "2025-01-31"
        title: "Developer Embedded Software"
      - name: "Thomas Hedler"
        birthday: "1973-12-19"
        title: "FW development professional"
      - name: "Markus Hoelzl"
        birthday: ""
        title: "Developer eSoftware"
  - name: "Coach"
    members:
      - name: "Mikkel Toudal Kristiansen"
        birthday: "1974-11-29"
        title: "Agile Coach"
      - name: "Swati Metya"
        birthday: ""
        title: "Improvement Coach"
  - name: "PMO"
    members:
      - name: "Andrei Backes"
        birthday: ""
        title: "Product Owner"
      - name: "Pavan Kantharaju"
        birthday: "1986-10-04"
        title: "Product Owner"
      - name: "Song Chen"
        birthday: ""
        title: "Product Owner"
      - name: "Toke Borgen Linander"
        birthday: ""
        title: "Project Lead"
      - name: "Rajeev Mahadevan"
        birthday: "2025-09-16"
        title: "Senior Product Owner"
      - name: "Torsten Brünnich Malajas"
        birthday: ""
        title: "Project Lead"
      - name: "Klaus Nehmiz"
        birthday: ""
        title: "Project Lead"
      - name: "Poul Erik Petersen"
        birthday: "1964-03-14"
        title: "Product Owner"
      - name: "Robert Skerjanc"
        birthday: ""
        title: "Product Owner"
      - name: "Prasenjeet Ghaywat"
        birthday: ""
        title: "Project Lead"
      - name: "Karsten Linzmeier"
        birthday: ""
        title: "Product Owner"
  - name: "Line"
    members:
      - name: "Thomas Fischer"
        birthday: "1977-01-25"
        title: "Senior Director"
      - name: "Thomas Alten"
        birthday: "2025-09-23"
        title: "Team Lead"
      - name: "Andrea Mijovic"
        birthday: "1988-07-20"
        title: "Line Manager"
      - name: "Kim Poulsen"
        birthday: "1974-03-04"
        title: "Senior Manager"
      - name: "Andre Schmelzer"
        birthday: "1987-06-14"
        title: "Team Lead"
      - name: "Joerg Schuler"
        birthday: ""
        title: "Line Manager"
      - name: "Henrik Stensig"
        birthday: "1969-10-24"
        title: "Senior Manager"
  - name: "Other"
    members:
      - name: "My Hanh Truong"
        birthday: ""
        title: "Working Student"
